services:
  proxy:
    image: nginx:alpine
    ports:
      - "80:80"

  frontend:
    image: nginx:alpine

  backend:
    build: ./backend
    container_name: boxer-backend
    ports:
      - "5000:5000"

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: boxing
